image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [565.23429,   0.     , 312.96335,
           0.     , 565.95252, 262.63097,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.396959, 0.119176, -0.007615, 0.003161, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [477.93326,   0.     , 312.81849,   0.     ,
           0.     , 520.40826, 263.09238,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
