medsnake:
  joint_state_controller:
    # The joint state controller handles publishing transforms for any moving joints
    type: joint_state_controller/JointStateController
    publish_rate: 50

  trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_inner
      - joint_outer
      - balljoint_1_0
      - balljoint_1_1
      - balljoint_2_0
      - balljoint_2_1
      - balljoint_3_0
      - balljoint_3_1
      - balljoint_4_0
      - balljoint_4_1
      - balljoint_5_0
      - balljoint_5_1
      - balljoint_6_0
      - balljoint_6_1
      - balljoint_7_0
      - balljoint_7_1
      - balljoint_8_0
      - balljoint_8_1
      - balljoint_9_0
      - balljoint_9_1
      - balljoint_10_0
      - balljoint_10_1
      - balljoint_11_0
      - balljoint_11_1
      - balljoint_12_0
      - balljoint_12_1
      - balljoint_13_0
      - balljoint_13_1
      - balljoint_14_0
      - balljoint_14_1
      - balljoint_15_0
      - balljoint_15_1
      - balljoint_16_0
      - balljoint_16_1
      - balljoint_17_0
      - balljoint_17_1
      - balljoint_18_0
      - balljoint_18_1
      - balljoint_19_0
      - balljoint_19_1
      - balljoint_20_0
      - balljoint_20_1
      - balljoint_21_0
      - balljoint_21_1
      - balljoint_22_0
      - balljoint_22_1
      - balljoint_23_0
      - balljoint_23_1
      - balljoint_24_0
      - balljoint_24_1
      - balljoint_25_0
      - balljoint_25_1
      - balljoint_26_0
      - balljoint_26_1
      - balljoint_27_0
      - balljoint_27_1
      - balljoint_28_0
      - balljoint_28_1
      - balljoint_29_0
      - balljoint_29_1
      - balljoint_30_0
      - balljoint_30_1
      



  # outerjoint_controller:
  #   joint: joint_outer
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # innerjoint_controller: 
  #   joint: joint_inner
  #   type: effor_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_1_0_controller:
  #   joint: balljoint_1_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_2_0_controller:
  #   joint: balljoint_2_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_3_0_controller:
  #   joint: balljoint_3_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_4_0_controller:
  #   joint: balljoint_4_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_5_0_controller:
  #   joint: balljoint_5_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}
  
  # balljoint_6_0_controller:
  #   joint: balljoint_6_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_7_0_controller:
  #   joint: balljoint_7_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}
  
  # balljoint_8_0_controller:
  #   joint: balljoint_8_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_9_0_controller:
  #   joint: balljoint_9_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_10_0_controller:
  #   joint: balljoint_10_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}

  # balljoint_11_0_controller:
  #   joint: balljoint_11_0
  #   type: effort_controllers/JointPositionController
  #   pid: {p: 50, i: 0, d: 10, i_clamp: 0}