<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manipulator">
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>
  <material name="blue">
    <color rgba="0 0 .8 1" />
  </material>
  <material name="yellow">
    <color rgba="1 1 0 1" />
  </material>
  <material name="green">
    <color rgba="0 1 0 1" />
  </material>
  <material name="orange">
    <color rgba="0.255 0.165 0 1" />
  </material>
  <material name="red">
    <color rgba="1 0 0 1" />
  </material>

  <xacro:property name="link_radius" value="0.005405" />
  <xacro:property name="link_length" value="0.00923" />
  <xacro:property name="num_links" value="30" />
  <xacro:property name="first_length" value="0.15" />
  <xacro:property name="first_radius" value="0.00923" />
  <xacro:property name="joint_limit" value="0.78" />
  
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <link name="world" />

  <joint name="world_to_base_link=" type="fixed">
      <parent link="world"/>
      <child link="base_link"/>
  </joint>

  <link name="base_link">
    <xacro:default_inertial mass="10"/>
    <visual>
      <geometry>
        <mesh filename="package://medsnake_sim/meshModel/base_part.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <origin rpy="1.5707963 0 -1.5707963" xyz="0.822 0.315 -0.22" />
      <material name="blue" />
    </visual>

    <static>1</static>
  </link>


  <joint name="joint_inner" type="prismatic">
    <parent link="base_link" />
    <child link="link_inner" />
    <origin rpy="1.5707963 0 1.5707963" xyz="0.1 0 0.04" />
    <limit effort="1000" lower="0" upper="0.35000000000000003" velocity="180" />
    <axis xyz="0 0 1" />
  </joint>

  <transmission name="inner_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="$inner_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="joint_inner">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <link name="link_inner">
    <inertial>
      <origin rpy="0 0 0" xyz="0 -0.016 0.161" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://medsnake_sim/meshModel/inner_part.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <origin rpy="0 3.1415926 0" xyz="0.315 -0.26 0.732" />
      <material name="red" />
    </visual>
    <static>1</static>
  </link>


  <joint name="joint_outer" type="prismatic">
    <parent link="base_link" />
    <child link="link_outer" />
    <origin rpy="1.5707963 0 1.5707963" xyz="0.2 0 0.04" />
    <limit effort="1000" lower="0" upper="0.35000000000000003" velocity="180" />
    <axis xyz="0 0 1" />
  </joint>

  <transmission name="outer_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="$outer_motor">
         <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="joint_outer">
       <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <link name="link_outer">
    <xacro:default_inertial mass="7.7"/>
    <visual>
      <geometry>
        <mesh filename="package://medsnake_sim/meshModel/outer_part.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <origin rpy="0 3.1415926 0" xyz="0.315 -0.26 0.662" />
      <material name="green" />
    </visual>
    <static>1</static>
  </link>

  <joint name="joint_snake" type="fixed">
    <parent link="link_outer" />
    <child link="link_0" />
    <origin rpy="0 0 0" xyz="-0.003 -0.0085 0.105" />
    <limit effort="1000" lower="0" upper="0.35000000000000003" velocity="180" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="link_0">
    <xacro:default_inertial mass="0.1"/>

    <visual>
      <geometry>
        <cylinder length="${first_length}" radius="${link_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${first_length/2}" />
      <material name="yellow" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${first_length}" radius="${first_radius}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${first_length/2}" />
    </collision>
  </link>

  <xacro:macro name="snake_piece" params="suffix">
    <xacro:unless value="${suffix == 0}">
      
      <link name="link_${suffix}">
        <xacro:default_inertial mass="0.1"/>
        <visual>
          <geometry>
            <!-- <cylinder length="${link_length}" radius="${link_radius}" /> -->
            <mesh filename="package://medsnake_sim/meshModel/snake_outer_link.STL" scale="0.001 0.001 0.001" />
          </geometry>
          <origin rpy="1.5707963 0 0" xyz="0 0 ${link_length/2}" />
          <material name="yellow" />
        </visual>
        <collision>
          <geometry>
            <cylinder length="${link_length}" radius="${link_radius}" />
          </geometry>
          <origin rpy="0 0 0" xyz="0 0 ${link_length/2}" />
        </collision>
      </link>

      <joint name="balljoint_${suffix}_0" type="revolute">
        <parent link="link_${suffix-1}" />
        <child link="zero_link_${suffix}_0" />
        <xacro:if value="${suffix ==1}">
          <origin rpy="0 0 0" xyz="0 0 ${first_length}" />
        </xacro:if>
        <xacro:unless value="${suffix == 1}">
          <origin rpy="0 0 0" xyz="0 0 ${link_length}" />
        </xacro:unless>
        <axis xyz="1 0 0" />
        <limit effort="1000.0" lower="-${joint_limit}" upper="${joint_limit}" velocity="0.5" />
      </joint>

      <transmission name="balljoint_${suffix}_0_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="$balljoint_${suffix}_0_motor">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="balljoint_${suffix}_0">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      </transmission>      

      <link name="zero_link_${suffix}_0">
        <xacro:default_inertial mass="0.1"/>
        <visual>
          <geometry>
            <cylinder length="0" radius="0" />
          </geometry>
          <origin rpy="0 0 0" xyz="0 0 0" />
        </visual>
        
        <collision>
        <geometry><box size="0 0 0" /></geometry>
        </collision>
      </link>

      <joint name="balljoint_${suffix}_1" type="revolute">
        <parent link="zero_link_${suffix}_0" />
        <child link="zero_link_${suffix}_1" />
        <origin rpy="0 0 0" xyz="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="-${joint_limit}" upper="${joint_limit}" velocity="0.5" />
      </joint>

      <transmission name="balljoint_${suffix}_1_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="$balljoint_${suffix}_1_motor">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="balljoint_${suffix}_1">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      </transmission>          

      <link name="zero_link_${suffix}_1">   
        <xacro:default_inertial mass="0.1"/>
        <visual>
          <geometry>
            <cylinder length="0" radius="0" />
          </geometry>
          <origin rpy="0 0 0" xyz="0 0 0" />
        </visual>

        <collision>
        <geometry><box size="0 0 0" /></geometry>
        </collision>
      </link>

      <joint name="balljoint_${suffix}_2" type="revolute">
        <parent link="zero_link_${suffix}_1" />
        <child link="link_${suffix}" />
        <origin rpy="0 0 0" xyz="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="-${joint_limit}" upper="${joint_limit}" velocity="0.5" />
      </joint>
    </xacro:unless>
  </xacro:macro>

  <xacro:macro name="loop" params="num_links">
    <xacro:snake_piece suffix="${num_links}" />
    <xacro:if value="${num_links}">
      <xacro:loop num_links="${num_links-1}" />
    </xacro:if>
  </xacro:macro>

  <xacro:loop num_links="${num_links}" />

  <joint name="camera_joint" type="fixed">
    <parent link="link_30" />
    <child link="camera_link" />
    <origin rpy="-1.570796 -1.570796 0" xyz="0 0 0" />
    <!-- <axis xyz="0 0 1" /> -->
  </joint>

  <link name="camera_link">
    <xacro:default_inertial mass="0.001"/>
    <visual>
      <!-- <geometry>
        <cylinder length="0.1" radius="0.001" />
      </geometry> -->
      <material name="red"/>
      <origin rpy="0 0 0" xyz="0 0 0" />
    </visual>

    <collision>
      <geometry><box size="0.01 0.01 0.01" /></geometry>
    </collision>
  </link>

  <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov> 
        <image>
          <width>800</width>
          <height>600</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>medsnake/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>
  <!-- <link name = "link_snake">
    <inertial>
      <origin rpy="0 0 0" xyz="0 -0.016 0.161"/>
      <mass value="7.7"/>
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://medsnake_sim/meshModel/snake_part.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.022 -0.02 -0.02"/>
      <material name="yellow"/>
    </visual>
  </link> -->

  <!-- <link name="test">
    <visual>
      <geometry>
        <cylinder length="0.3" radius="0.02" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.15" />
      <material name="yellow" />
    </visual>
  </link>

  <joint name="balljoint_1" type="revolute">
    <parent link="test" />
    <child link="test2" />
    <origin rpy="0 0 0" xyz="0 0 0.3" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.5" />
  </joint>
  <joint name="balljoint_2" type="revolute">
    <parent link="test2" />
    <child link="test3" />
    <origin rpy="0 0 0" xyz="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.5" />
  </joint>
  <joint name="balljoint_3" type="revolute">
    <parent link="test3" />
    <child link="test4" />
    <origin rpy="0 0 0" xyz="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.5" />
  </joint>
  <joint name="balljoint_4" type="revolute">
    <parent link="test4" />
    <child link="test5" />
    <origin rpy="0 0 0" xyz="0 0 0.1" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.5" />
  </joint>
  <joint name="balljoint_5" type="revolute">
    <parent link="test5" />
    <child link="test6" />
    <origin rpy="0 0 0" xyz="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.5" />
  </joint>
  <joint name="balljoint_6" type="revolute">
    <parent link="test6" />
    <child link="test7" />
    <origin rpy="0 0 0" xyz="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" lower="-0.548" upper="0.548" velocity="0.5" />
  </joint>
  <link name="test2">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0" radius="0" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <material name="yellow" />
    </visual>
  </link>
  <link name="test3">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0" radius="0" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <material name="yellow" />
    </visual>
  </link>
  <link name="test4">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.02" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.05" />
      <material name="yellow" />
    </visual>
  </link>
  <link name="test5">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0" radius="0" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <material name="yellow" />
    </visual>
  </link>
  <link name="test6">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0" radius="0" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <material name="yellow" />
    </visual>
  </link>
  <link name="test7">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="7.7" />
      <inertia ixx="0.06718763333333333" ixy="0" ixz="0" iyy="0.06653056666666667" iyz="0" izz="0.0006570666666666666" />
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.02" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.05" />
      <material name="yellow" />
    </visual>
  </link> -->

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/medsnake</robotNamespace>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName> balljoint_1_0, balljoint_2_0 </jointName>
      <robotNamespace>/medsnake</robotNamespace>
      <updateRate>50.0</updateRate>
      <alwaysOn>true</alwaysOn>
    </plugin>
  </gazebo>
</robot>